export const categorySeeds = [
  { key: 'daily_cleaning', name: '日常保洁', icon: 'i-carbon-clean', sortOrder: 1 },
  { key: 'deep_cleaning', name: '深度清洁', icon: 'i-carbon-tools', sortOrder: 2 },
  { key: 'post_renovation_cleaning', name: '开荒保洁', icon: 'i-carbon-clean', sortOrder: 3 },
  { key: 'kitchen_deep_cleaning', name: '厨房深度', icon: 'i-carbon-clean', sortOrder: 4 },
  { key: 'appliance_cleaning', name: '家电清洗', icon: 'i-carbon-clean', sortOrder: 5 },
  { key: 'curtain_cleaning', name: '窗帘清洗', icon: 'i-carbon-clean', sortOrder: 6 },
  { key: 'clothing_care', name: '衣服洗护', icon: 'i-carbon-store', sortOrder: 7 },
  { key: 'storage_organizing', name: '收纳整理', icon: 'i-carbon-store', sortOrder: 8 },
  { key: 'furniture_care', name: '家具养护', icon: 'i-carbon-home', sortOrder: 9 },
  { key: 'pest_disinfection', name: '杀虫消毒', icon: 'i-carbon-security', sortOrder: 10 },
  { key: 'home_repair', name: '上门维修', icon: 'i-carbon-tools', sortOrder: 11 },
  { key: 'moving_delivery', name: '搬家拉货', icon: 'i-carbon-delivery', sortOrder: 12 },
  { key: 'nanny_maternity', name: '保姆月嫂', icon: 'i-carbon-user-avatar', sortOrder: 13 },
  { key: 'pet_service', name: '爱宠服务', icon: 'i-carbon-pet-image-b', sortOrder: 14 },
]

export const serviceSeeds = [
  { categoryKey: 'daily_cleaning', name: '日常保洁 2 小时', description: '适合小户型基础清洁，覆盖客厅、卧室、厨房台面和卫生间基础清洁。', basePrice: '120', priceUnit: '次', sortOrder: 1 },
  { categoryKey: 'daily_cleaning', name: '日常保洁 3 小时', description: '适合标准家庭日常维护清洁，包含地面、台面、厨卫基础清洁。', basePrice: '170', priceUnit: '次', sortOrder: 2 },
  { categoryKey: 'daily_cleaning', name: '日常保洁 4 小时', description: '适合大户型或重点区域加强清洁。', basePrice: '220', priceUnit: '次', sortOrder: 3 },
  { categoryKey: 'deep_cleaning', name: '深度清洁 4 小时', description: '针对厨卫、客厅等重点区域进行深度清洁。', basePrice: '260', priceUnit: '次', sortOrder: 4 },
  { categoryKey: 'deep_cleaning', name: '全屋深度清洁', description: '全屋多区域深度清洁，适合周期性大扫除。', basePrice: '380', priceUnit: '次', sortOrder: 5 },
  { categoryKey: 'deep_cleaning', name: '厨卫深度清洁套餐', description: '厨房和卫生间重点清洁，处理水垢、油污和卫生死角。', basePrice: '299', priceUnit: '次', sortOrder: 6 },
  { categoryKey: 'post_renovation_cleaning', name: '新居开荒保洁', description: '新房装修后首次清洁，清理灰尘、胶印和装修残留。', basePrice: '399', priceUnit: '次', sortOrder: 7 },
  { categoryKey: 'post_renovation_cleaning', name: '开荒保洁按面积计费', description: '适合大面积新房、办公室或商铺开荒保洁。', basePrice: '8', priceUnit: '平米', sortOrder: 8 },
  { categoryKey: 'kitchen_deep_cleaning', name: '厨房深度清洁', description: '清洁灶台、台面、墙面、橱柜外部和厨房地面。', basePrice: '199', priceUnit: '次', sortOrder: 9 },
  { categoryKey: 'kitchen_deep_cleaning', name: '重油污厨房清洁', description: '针对长期油污堆积厨房进行强化处理。', basePrice: '299', priceUnit: '次', sortOrder: 10 },
  { categoryKey: 'appliance_cleaning', name: '空调清洗', description: '挂机空调滤网、蒸发器和外壳清洁。', basePrice: '99', priceUnit: '台', sortOrder: 11 },
  { categoryKey: 'appliance_cleaning', name: '油烟机清洗', description: '油烟机外壳、滤网、油杯和可拆部件清洗。', basePrice: '159', priceUnit: '台', sortOrder: 12 },
  { categoryKey: 'appliance_cleaning', name: '洗衣机清洗', description: '滚筒或波轮洗衣机内筒深度清洁。', basePrice: '129', priceUnit: '台', sortOrder: 13 },
  { categoryKey: 'appliance_cleaning', name: '冰箱清洗', description: '冰箱内部除味、除污和外部清洁。', basePrice: '139', priceUnit: '台', sortOrder: 14 },
  { categoryKey: 'curtain_cleaning', name: '窗帘上门拆洗', description: '提供窗帘拆卸、清洗和安装服务。', basePrice: '20', priceUnit: '平米', sortOrder: 15 },
  { categoryKey: 'curtain_cleaning', name: '窗帘除尘护理', description: '轻度除尘和日常护理，适合定期维护。', basePrice: '99', priceUnit: '次', sortOrder: 16 },
  { categoryKey: 'clothing_care', name: '衣服取送洗护', description: '上门取送衣物，按件或订单计费。', basePrice: '39', priceUnit: '单', sortOrder: 17 },
  { categoryKey: 'clothing_care', name: '大件衣物洗护', description: '羽绒服、大衣等大件衣物洗护。', basePrice: '59', priceUnit: '件', sortOrder: 18 },
  { categoryKey: 'clothing_care', name: '床品洗护', description: '被套、床单、四件套等床品洗护。', basePrice: '49', priceUnit: '件', sortOrder: 19 },
  { categoryKey: 'storage_organizing', name: '衣柜收纳整理', description: '衣柜分区、折叠、分类和收纳优化。', basePrice: '199', priceUnit: '次', sortOrder: 20 },
  { categoryKey: 'storage_organizing', name: '厨房收纳整理', description: '厨房用品分类、收纳动线整理。', basePrice: '199', priceUnit: '次', sortOrder: 21 },
  { categoryKey: 'storage_organizing', name: '全屋收纳整理', description: '多空间收纳规划和整理服务。', basePrice: '499', priceUnit: '次', sortOrder: 22 },
  { categoryKey: 'furniture_care', name: '沙发清洗养护', description: '布艺或皮质沙发清洁护理。', basePrice: '199', priceUnit: '次', sortOrder: 23 },
  { categoryKey: 'furniture_care', name: '床垫除螨养护', description: '床垫吸尘、除螨和护理。', basePrice: '169', priceUnit: '张', sortOrder: 24 },
  { categoryKey: 'furniture_care', name: '木质家具养护', description: '木质家具表面清洁和基础养护。', basePrice: '199', priceUnit: '次', sortOrder: 25 },
  { categoryKey: 'pest_disinfection', name: '全屋杀虫消毒', description: '家庭常见虫害处理和消毒服务。', basePrice: '299', priceUnit: '次', sortOrder: 26 },
  { categoryKey: 'pest_disinfection', name: '厨卫蟑螂治理', description: '厨房和卫生间重点灭蟑治理。', basePrice: '199', priceUnit: '次', sortOrder: 27 },
  { categoryKey: 'pest_disinfection', name: '除螨消毒', description: '床垫、沙发、地毯等区域除螨消毒。', basePrice: '169', priceUnit: '次', sortOrder: 28 },
  { categoryKey: 'home_repair', name: '水龙头维修', description: '水龙头漏水、松动和基础更换维修。', basePrice: '80', priceUnit: '次', sortOrder: 29 },
  { categoryKey: 'home_repair', name: '电路维修', description: '开关插座更换、线路检查和基础维修。', basePrice: '100', priceUnit: '次', sortOrder: 30 },
  { categoryKey: 'home_repair', name: '家具小修', description: '门锁、合页、家具配件等小修服务。', basePrice: '120', priceUnit: '次', sortOrder: 31 },
  { categoryKey: 'moving_delivery', name: '居民搬家', description: '同城居民搬家，含基础搬运。', basePrice: '300', priceUnit: '次', sortOrder: 32 },
  { categoryKey: 'moving_delivery', name: '小件拉货', description: '同城小件运输和拉货服务。', basePrice: '120', priceUnit: '次', sortOrder: 33 },
  { categoryKey: 'moving_delivery', name: '搬运工服务', description: '单独搬运人力服务，按小时计费。', basePrice: '80', priceUnit: '小时', sortOrder: 34 },
  { categoryKey: 'nanny_maternity', name: '住家保姆咨询', description: '住家保姆需求登记，后续人工报价。', basePrice: '0', priceUnit: '咨询', sortOrder: 35 },
  { categoryKey: 'nanny_maternity', name: '月嫂服务咨询', description: '月嫂服务需求登记，后续人工报价。', basePrice: '0', priceUnit: '咨询', sortOrder: 36 },
  { categoryKey: 'nanny_maternity', name: '育儿嫂服务咨询', description: '育儿嫂服务需求登记，后续人工报价。', basePrice: '0', priceUnit: '咨询', sortOrder: 37 },
  { categoryKey: 'pet_service', name: '宠物上门喂养', description: '上门喂食、换水和基础照看。', basePrice: '59', priceUnit: '次', sortOrder: 38 },
  { categoryKey: 'pet_service', name: '宠物陪伴照看', description: '短时宠物陪伴和照看服务。', basePrice: '99', priceUnit: '次', sortOrder: 39 },
  { categoryKey: 'pet_service', name: '宠物用品清洁', description: '猫砂盆、宠物垫等宠物用品清洁。', basePrice: '89', priceUnit: '次', sortOrder: 40 },
]
