type ServiceCardType = 'time' | 'times' | 'none' | 'consultation'

export interface ServiceSeed {
  categoryKey: string
  name: string
  description: string
  basePrice: string
  priceUnit: string
  sortOrder: number
  durationMinutes?: number | null
  cardType?: ServiceCardType
  consumeUnit?: number | null
  consultationRequired?: boolean
  coverImage?: string
}

export const categorySeeds = [
  { key: 'campaign', name: '特惠体验', icon: 'i-carbon-percentage', sortOrder: 1 },
  { key: 'daily_cleaning', name: '家居保洁', icon: 'i-carbon-clean', sortOrder: 2 },
  { key: 'appliance_cleaning', name: '家电清洗', icon: 'i-carbon-machine-learning-model', sortOrder: 3 },
  { key: 'soft_cleaning', name: '软装清洗', icon: 'i-carbon-software-resource', sortOrder: 4 },
  { key: 'deep_cleaning', name: '精细保洁', icon: 'i-carbon-tools', sortOrder: 5 },
  { key: 'glass_cleaning', name: '玻璃清洁', icon: 'i-carbon-sun', sortOrder: 6 },
  { key: 'business_cleaning', name: '企业保洁', icon: 'i-carbon-building', sortOrder: 7 },
  { key: 'home_repair', name: '水电维修', icon: 'i-carbon-tool-box', sortOrder: 8 },
]

const serviceCoverBaseUrl = 'https://gym-face-bucket.oss-cn-shenzhen.aliyuncs.com/life-assitant/dev/service_cover/admin/generated/2026/07'

export const serviceSeeds: ServiceSeed[] = [
  {
    categoryKey: 'campaign',
    name: '日常保洁 2 小时体验',
    description: '海报特惠体验服务，每户限享一次；适合客厅、卧室、厨房台面、卫生间基础清洁。',
    basePrice: '67',
    priceUnit: '次',
    sortOrder: 1,
    durationMinutes: 120,
    cardType: 'time',
    consumeUnit: 120,
    coverImage: `${serviceCoverBaseUrl}/daily-cleaning-trial.png`,
  },
  {
    categoryKey: 'campaign',
    name: '热水器深度清洗体验',
    description: '海报引流体验服务，适合热水器内胆、管路和外壳基础清洗，特殊机型需现场确认。',
    basePrice: '39',
    priceUnit: '台',
    sortOrder: 2,
    cardType: 'times',
    consumeUnit: 1,
    coverImage: `${serviceCoverBaseUrl}/water-heater-cleaning-trial.png`,
  },
  {
    categoryKey: 'daily_cleaning',
    name: '日常保洁 2 小时',
    description: '标准 2 小时家庭保洁，覆盖地面、台面、厨卫基础清洁，适合小户型或局部维护。',
    basePrice: '99',
    priceUnit: '次',
    sortOrder: 3,
    durationMinutes: 120,
    cardType: 'time',
    consumeUnit: 120,
    coverImage: `${serviceCoverBaseUrl}/daily-cleaning-2h.png`,
  },
  {
    categoryKey: 'daily_cleaning',
    name: '日常保洁 3 小时',
    description: '标准家庭日常维护清洁，适合两室或重点区域较多的家庭。',
    basePrice: '149',
    priceUnit: '次',
    sortOrder: 4,
    durationMinutes: 180,
    cardType: 'time',
    consumeUnit: 180,
    coverImage: `${serviceCoverBaseUrl}/daily-cleaning-3h.png`,
  },
  {
    categoryKey: 'daily_cleaning',
    name: '日常保洁 4 小时',
    description: '适合大户型、多人家庭或周期性保洁，覆盖更多重点区域。',
    basePrice: '199',
    priceUnit: '次',
    sortOrder: 5,
    durationMinutes: 240,
    cardType: 'time',
    consumeUnit: 240,
    coverImage: `${serviceCoverBaseUrl}/daily-cleaning-4h.png`,
  },
  {
    categoryKey: 'daily_cleaning',
    name: '厨卫重点保洁',
    description: '厨房台面、灶台、卫生间洁具、水垢和地面重点清洁。',
    basePrice: '169',
    priceUnit: '次',
    sortOrder: 6,
    cardType: 'times',
    consumeUnit: 1,
    coverImage: `${serviceCoverBaseUrl}/kitchen-bathroom-cleaning.png`,
  },
  {
    categoryKey: 'appliance_cleaning',
    name: '油烟机深度清洗',
    description: '油烟机外壳、滤网、油杯和可拆部件清洗，重油污另行确认。',
    basePrice: '159',
    priceUnit: '台',
    sortOrder: 7,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'appliance_cleaning',
    name: '洗衣机深度清洗',
    description: '滚筒或波轮洗衣机内筒清洁、除垢和除味。',
    basePrice: '129',
    priceUnit: '台',
    sortOrder: 8,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'appliance_cleaning',
    name: '空调挂机清洗',
    description: '挂机空调滤网、蒸发器和外壳清洁，多台可叠加预约。',
    basePrice: '99',
    priceUnit: '台',
    sortOrder: 9,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'appliance_cleaning',
    name: '热水器深度清洗',
    description: '热水器内胆、管路和外壳深度清洁，适合长期未清洗设备。',
    basePrice: '99',
    priceUnit: '台',
    sortOrder: 10,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'appliance_cleaning',
    name: '冰箱清洗除味',
    description: '冰箱内部除味、隔板清洁和外部擦拭。',
    basePrice: '139',
    priceUnit: '台',
    sortOrder: 11,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'soft_cleaning',
    name: '沙发清洗',
    description: '布艺沙发吸尘、表面清洗和基础护理，皮质材质需现场确认。',
    basePrice: '199',
    priceUnit: '次',
    sortOrder: 12,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'soft_cleaning',
    name: '床垫除螨清洗',
    description: '床垫吸尘、除螨和表面护理，适合家庭定期维护。',
    basePrice: '169',
    priceUnit: '张',
    sortOrder: 13,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'soft_cleaning',
    name: '窗帘上门拆洗',
    description: '窗帘拆卸、清洗和安装，按面积计价，复杂轨道另行确认。',
    basePrice: '20',
    priceUnit: '平米',
    sortOrder: 14,
    cardType: 'none',
    consumeUnit: null,
  },
  {
    categoryKey: 'soft_cleaning',
    name: '地毯清洗',
    description: '家用地毯吸尘、局部清洁和护理，材质特殊需现场确认。',
    basePrice: '15',
    priceUnit: '平米',
    sortOrder: 15,
    cardType: 'none',
    consumeUnit: null,
  },
  {
    categoryKey: 'deep_cleaning',
    name: '全屋精细保洁',
    description: '全屋多区域精细清洁，适合周期性大扫除或节前清洁。',
    basePrice: '399',
    priceUnit: '次',
    sortOrder: 16,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'deep_cleaning',
    name: '厨房重油污深度清洁',
    description: '针对长期油污堆积厨房，处理灶台、墙面、台面和死角。',
    basePrice: '299',
    priceUnit: '次',
    sortOrder: 17,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'deep_cleaning',
    name: '卫生间水垢深度清洁',
    description: '卫生间洁具、水垢、玻璃隔断和地面缝隙重点清洁。',
    basePrice: '199',
    priceUnit: '次',
    sortOrder: 18,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'deep_cleaning',
    name: '新居开荒保洁',
    description: '新房装修后首次清洁，清理灰尘、胶印和装修残留。',
    basePrice: '8',
    priceUnit: '平米',
    sortOrder: 19,
    cardType: 'none',
    consumeUnit: null,
  },
  {
    categoryKey: 'glass_cleaning',
    name: '居家玻璃清洁',
    description: '家庭窗户、阳台玻璃和窗框清洁，按面积计费。',
    basePrice: '8',
    priceUnit: '平米',
    sortOrder: 20,
    cardType: 'none',
    consumeUnit: null,
  },
  {
    categoryKey: 'glass_cleaning',
    name: '高层玻璃清洁',
    description: '高层或外侧玻璃清洁，需先确认作业条件和安全边界。',
    basePrice: '12',
    priceUnit: '平米',
    sortOrder: 21,
    cardType: 'none',
    consumeUnit: null,
  },
  {
    categoryKey: 'business_cleaning',
    name: '办公室日常保洁咨询',
    description: '企业、办公室、门店日常保洁需求登记，按面积和频次人工报价。',
    basePrice: '0',
    priceUnit: '咨询',
    sortOrder: 22,
    cardType: 'consultation',
    consumeUnit: null,
    consultationRequired: true,
  },
  {
    categoryKey: 'business_cleaning',
    name: '企业开荒保洁咨询',
    description: '办公室、商铺、厂房等开荒保洁需求登记，现场评估后报价。',
    basePrice: '0',
    priceUnit: '咨询',
    sortOrder: 23,
    cardType: 'consultation',
    consumeUnit: null,
    consultationRequired: true,
  },
  {
    categoryKey: 'home_repair',
    name: '水龙头角阀维修',
    description: '水龙头、角阀漏水或松动维修，材料费另计。',
    basePrice: '80',
    priceUnit: '次',
    sortOrder: 24,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'home_repair',
    name: '开关插座更换',
    description: '开关、插座基础更换和线路检查，材料费另计。',
    basePrice: '80',
    priceUnit: '次',
    sortOrder: 25,
    cardType: 'times',
    consumeUnit: 1,
  },
  {
    categoryKey: 'home_repair',
    name: '灯具安装维修',
    description: '吸顶灯、简易吊灯安装或基础维修，复杂灯具现场确认。',
    basePrice: '100',
    priceUnit: '次',
    sortOrder: 26,
    cardType: 'times',
    consumeUnit: 1,
  },
]
