export const ADMIN_ROLE = {
  SUPER_ADMIN: 'super_admin',
  OPERATOR: 'operator',
  FINANCE: 'finance',
} as const

export type AdminRole = typeof ADMIN_ROLE[keyof typeof ADMIN_ROLE]

export const ADMIN_ROLE_RESPONSE = {
  [ADMIN_ROLE.SUPER_ADMIN]: 'SUPER_ADMIN',
  [ADMIN_ROLE.OPERATOR]: 'OPERATOR',
  [ADMIN_ROLE.FINANCE]: 'FINANCE',
} as const

export const ADMIN_PERMISSION = {
  DASHBOARD_VIEW: 'dashboard:view',
  USER_LIST: 'user:list',
  USER_DETAIL: 'user:detail',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_ROLE_UPDATE: 'user:role:update',
  SERVICE_LIST: 'service:list',
  SERVICE_CREATE: 'service:create',
  SERVICE_UPDATE: 'service:update',
  SERVICE_DELETE: 'service:delete',
  ORDER_LIST: 'order:list',
  ORDER_DETAIL: 'order:detail',
  ORDER_UPDATE: 'order:update',
  ORDER_DELETE: 'order:delete',
  ORDER_ASSIGN: 'order:assign',
  STAFF_LIST: 'staff:list',
  STAFF_CREATE: 'staff:create',
  STAFF_UPDATE: 'staff:update',
  STAFF_DELETE: 'staff:delete',
  STAFF_AUDIT: 'staff:audit',
  FINANCE_PAYMENT_LIST: 'finance:payment:list',
  FINANCE_REFUND_LIST: 'finance:refund:list',
  FINANCE_REFUND_AUDIT: 'finance:refund:audit',
  FINANCE_REFUND_RETRY: 'finance:refund:retry',
  FINANCE_WITHDRAW_LIST: 'finance:withdraw:list',
  FINANCE_WITHDRAW_DETAIL: 'finance:withdraw:detail',
  FINANCE_WITHDRAW_AUDIT: 'finance:withdraw:audit',
  FINANCE_WITHDRAW_EXECUTE: 'finance:withdraw:execute',
  FINANCE_WITHDRAW_RETRY: 'finance:withdraw:retry',
  FINANCE_WITHDRAW_RECONCILE: 'finance:withdraw:reconcile',
  AFTER_SALES_TICKET_LIST: 'after-sales:ticket:list',
  AFTER_SALES_TICKET_DETAIL: 'after-sales:ticket:detail',
  AFTER_SALES_TICKET_REPLY: 'after-sales:ticket:reply',
  AFTER_SALES_TICKET_RESOLVE: 'after-sales:ticket:resolve',
  AFTER_SALES_FEEDBACK_LIST: 'after-sales:feedback:list',
  AFTER_SALES_FEEDBACK_REPLY: 'after-sales:feedback:reply',
  AFTER_SALES_FEEDBACK_RESOLVE: 'after-sales:feedback:resolve',
  SUPPORT_CONTENT_LIST: 'support:content:list',
  SUPPORT_CONTENT_CREATE: 'support:content:create',
  SUPPORT_CONTENT_UPDATE: 'support:content:update',
  SUPPORT_CONTENT_DELETE: 'support:content:delete',
  MARKETING_COUPON_LIST: 'marketing:coupon:list',
  MARKETING_COUPON_CREATE: 'marketing:coupon:create',
  MARKETING_COUPON_UPDATE: 'marketing:coupon:update',
  MARKETING_COUPON_DELETE: 'marketing:coupon:delete',
  MARKETING_PROMOTION_LIST: 'marketing:promotion:list',
  MARKETING_PROMOTION_CREATE: 'marketing:promotion:create',
  MARKETING_PROMOTION_UPDATE: 'marketing:promotion:update',
  MARKETING_PROMOTION_DELETE: 'marketing:promotion:delete',
  MEMBER_CARD_LIST: 'member-card:list',
  MEMBER_CARD_CREATE: 'member-card:create',
  MEMBER_CARD_UPDATE: 'member-card:update',
  MEMBER_CARD_GRANT: 'member-card:grant',
  ADDRESS_LIST: 'address:list',
  ADDRESS_CREATE: 'address:create',
  ADDRESS_UPDATE: 'address:update',
  ADDRESS_DELETE: 'address:delete',
  REVIEW_LIST: 'review:list',
  REVIEW_UPDATE: 'review:update',
  AUDIT_CENTER_LIST: 'audit-center:list',
  AUDIT_CENTER_REVIEW: 'audit-center:review',
  AUDIT_LOG_LIST: 'audit-log:list',
  IMAGE_LIST: 'image:list',
  IMAGE_DETAIL: 'image:detail',
  IMAGE_UPDATE: 'image:update',
  IMAGE_DELETE: 'image:delete',
  IMAGE_REBIND: 'image:rebind',
  IMAGE_BACKFILL: 'image:backfill',
} as const

const OPERATOR_PERMISSIONS = [
  ADMIN_PERMISSION.DASHBOARD_VIEW,
  ADMIN_PERMISSION.USER_LIST,
  ADMIN_PERMISSION.USER_DETAIL,
  ADMIN_PERMISSION.USER_UPDATE,
  ADMIN_PERMISSION.SERVICE_LIST,
  ADMIN_PERMISSION.SERVICE_CREATE,
  ADMIN_PERMISSION.SERVICE_UPDATE,
  ADMIN_PERMISSION.ORDER_LIST,
  ADMIN_PERMISSION.ORDER_DETAIL,
  ADMIN_PERMISSION.ORDER_UPDATE,
  ADMIN_PERMISSION.ORDER_ASSIGN,
  ADMIN_PERMISSION.STAFF_LIST,
  ADMIN_PERMISSION.STAFF_CREATE,
  ADMIN_PERMISSION.STAFF_UPDATE,
  ADMIN_PERMISSION.STAFF_AUDIT,
  ADMIN_PERMISSION.ADDRESS_LIST,
  ADMIN_PERMISSION.ADDRESS_CREATE,
  ADMIN_PERMISSION.ADDRESS_UPDATE,
  ADMIN_PERMISSION.REVIEW_LIST,
  ADMIN_PERMISSION.REVIEW_UPDATE,
  ADMIN_PERMISSION.AFTER_SALES_TICKET_LIST,
  ADMIN_PERMISSION.AFTER_SALES_TICKET_DETAIL,
  ADMIN_PERMISSION.AFTER_SALES_TICKET_REPLY,
  ADMIN_PERMISSION.AFTER_SALES_TICKET_RESOLVE,
  ADMIN_PERMISSION.AFTER_SALES_FEEDBACK_LIST,
  ADMIN_PERMISSION.AFTER_SALES_FEEDBACK_REPLY,
  ADMIN_PERMISSION.AFTER_SALES_FEEDBACK_RESOLVE,
  ADMIN_PERMISSION.SUPPORT_CONTENT_LIST,
  ADMIN_PERMISSION.SUPPORT_CONTENT_CREATE,
  ADMIN_PERMISSION.SUPPORT_CONTENT_UPDATE,
  ADMIN_PERMISSION.SUPPORT_CONTENT_DELETE,
  ADMIN_PERMISSION.AUDIT_CENTER_LIST,
  ADMIN_PERMISSION.AUDIT_CENTER_REVIEW,
  ADMIN_PERMISSION.IMAGE_LIST,
  ADMIN_PERMISSION.IMAGE_DETAIL,
  ADMIN_PERMISSION.IMAGE_UPDATE,
  ADMIN_PERMISSION.IMAGE_DELETE,
]

const FINANCE_PERMISSIONS = [
  ADMIN_PERMISSION.DASHBOARD_VIEW,
  ADMIN_PERMISSION.ORDER_LIST,
  ADMIN_PERMISSION.ORDER_DETAIL,
  ADMIN_PERMISSION.FINANCE_PAYMENT_LIST,
  ADMIN_PERMISSION.FINANCE_REFUND_LIST,
  ADMIN_PERMISSION.FINANCE_REFUND_AUDIT,
  ADMIN_PERMISSION.FINANCE_REFUND_RETRY,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_LIST,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_DETAIL,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_AUDIT,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_EXECUTE,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_RETRY,
  ADMIN_PERMISSION.FINANCE_WITHDRAW_RECONCILE,
  ADMIN_PERMISSION.AUDIT_CENTER_LIST,
  ADMIN_PERMISSION.AUDIT_CENTER_REVIEW,
  ADMIN_PERMISSION.AUDIT_LOG_LIST,
  ADMIN_PERMISSION.IMAGE_LIST,
  ADMIN_PERMISSION.IMAGE_DETAIL,
]

export function normalizeAdminRole(role: string | null | undefined): AdminRole {
  if (role === ADMIN_ROLE.OPERATOR || role === ADMIN_ROLE.FINANCE) return role
  return ADMIN_ROLE.SUPER_ADMIN
}

export function getAdminRoles(role: string | null | undefined): string[] {
  const normalized = normalizeAdminRole(role)
  return [ADMIN_ROLE_RESPONSE[normalized]]
}

export function getAdminPermissions(role: string | null | undefined): string[] {
  const normalized = normalizeAdminRole(role)
  if (normalized === ADMIN_ROLE.SUPER_ADMIN) return ['*']
  if (normalized === ADMIN_ROLE.FINANCE) return FINANCE_PERMISSIONS
  return OPERATOR_PERMISSIONS
}
