import type { RouteItem } from "@/api/system/menu";

export const lifeAdminRoutes: RouteItem[] = [
  {
    path: "/users",
    component: "Layout",
    redirect: "/users/list",
    name: "LifeUsers",
    meta: { title: "用户管理", icon: "user", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "list",
        component: "life/resource/index",
        name: "LifeUserList",
        meta: { title: "用户列表", icon: "user", keepAlive: true, params: { module: "users" } },
        children: [],
      },
      {
        path: "addresses",
        component: "life/resource/index",
        name: "LifeAddressList",
        meta: { title: "地址管理", icon: "menu", keepAlive: true, params: { module: "addresses" } },
        children: [],
      },
    ],
  },
  {
    path: "/services",
    component: "Layout",
    redirect: "/services/categories",
    name: "LifeServices",
    meta: { title: "服务管理", icon: "project", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "categories",
        component: "life/resource/index",
        name: "LifeServiceCategories",
        meta: { title: "服务分类", icon: "cascader", keepAlive: true, params: { module: "serviceCategories" } },
        children: [],
      },
      {
        path: "items",
        component: "life/resource/index",
        name: "LifeServiceItems",
        meta: { title: "服务项目", icon: "project", keepAlive: true, params: { module: "services" } },
        children: [],
      },
    ],
  },
  {
    path: "/orders",
    component: "Layout",
    redirect: "/orders/list",
    name: "LifeOrders",
    meta: { title: "订单管理", icon: "table", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "list",
        component: "life/orders/index",
        name: "LifeOrderList",
        meta: { title: "服务预约订单", icon: "table", keepAlive: true, params: { orderType: "bookings" } },
        children: [],
      },
      {
        path: "member-card-orders",
        component: "life/orders/index",
        name: "LifeMemberCardPurchaseOrders",
        meta: { title: "会员卡购买订单", icon: "table", keepAlive: true, params: { orderType: "member_card_purchase" } },
        children: [],
      },
      {
        path: "dispatch",
        component: "life/orders/index",
        name: "LifeOrderDispatch",
        meta: { title: "待派单", icon: "todo", keepAlive: true, params: { status: "pending_dispatch", orderType: "bookings" } },
        children: [],
      },
      {
        path: "fulfillment",
        component: "life/resource/index",
        name: "LifeOrderFulfillment",
        meta: { title: "履约记录", icon: "document", keepAlive: true, params: { module: "fulfillments" } },
        children: [],
      },
      {
        path: "detail/:id",
        component: "life/orders/detail",
        name: "LifeOrderDetail",
        meta: { title: "订单详情", icon: "document", hidden: true, params: {} },
        children: [],
      },
    ],
  },
  {
    path: "/staff",
    component: "Layout",
    redirect: "/staff/list",
    name: "LifeStaff",
    meta: { title: "师傅管理", icon: "client", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "list",
        component: "life/resource/index",
        name: "LifeStaffList",
        meta: { title: "师傅列表", icon: "client", keepAlive: true, params: { module: "staff" } },
        children: [],
      },
      {
        path: "audit",
        component: "life/audit/index",
        name: "LifeStaffAudit",
        meta: { title: "认证审核", icon: "todo", keepAlive: true, params: { type: "staff" } },
        children: [],
      },
      {
        path: "status",
        component: "life/resource/index",
        name: "LifeStaffStatus",
        meta: { title: "工作状态", icon: "monitor", keepAlive: true, params: { module: "staffStatus" } },
        children: [],
      },
      {
        path: "notifications",
        component: "life/staff/notifications",
        name: "LifeStaffNotifications",
        meta: { title: "师傅通知", icon: "message", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "profile-changes",
        component: "life/staff/profile-changes",
        name: "LifeStaffProfileChanges",
        meta: { title: "资料变更复核", icon: "todo", keepAlive: true, params: {} },
        children: [],
      },
    ],
  },
  {
    path: "/finance",
    component: "Layout",
    redirect: "/finance/statistics",
    name: "LifeFinance",
    meta: { title: "财务管理", icon: "monitor", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "statistics",
        component: "life/finance/statistics",
        name: "LifeFinanceStatistics",
        meta: { title: "财务统计", icon: "monitor", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "payments",
        component: "life/resource/index",
        name: "LifePayments",
        meta: { title: "支付记录", icon: "monitor", keepAlive: true, params: { module: "payments" } },
        children: [],
      },
      {
        path: "points",
        component: "life/resource/index",
        name: "LifePointLedgers",
        meta: { title: "积分流水", icon: "document", keepAlive: true, params: { module: "pointLedgers" } },
        children: [],
      },
      {
        path: "refunds",
        component: "life/audit/index",
        name: "LifeRefundAudit",
        meta: { title: "退款审核", icon: "todo", keepAlive: true, params: { type: "refund" } },
        children: [],
      },
      {
        path: "withdraws",
        component: "life/finance/withdraws",
        name: "LifeWithdrawAudit",
        meta: { title: "提现管理", icon: "todo", keepAlive: true, params: { type: "withdraw" } },
        children: [],
      },
    ],
  },
  {
    path: "/after-sales",
    component: "Layout",
    redirect: "/after-sales/reviews",
    name: "LifeAfterSales",
    meta: { title: "评价与售后", icon: "message", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "reviews",
        component: "life/resource/index",
        name: "LifeReviews",
        meta: { title: "用户评价", icon: "message", keepAlive: true, params: { module: "reviews" } },
        children: [],
      },
      {
        path: "tickets",
        component: "life/audit/index",
        name: "LifeTicketAudit",
        meta: { title: "售后工单", icon: "todo", keepAlive: true, params: { type: "ticket" } },
        children: [],
      },
      {
        path: "feedbacks",
        component: "life/resource/index",
        name: "LifeFeedbacks",
        meta: { title: "问题反馈", icon: "message", keepAlive: true, params: { module: "feedbacks" } },
        children: [],
      },
      {
        path: "faqs",
        component: "life/resource/index",
        name: "LifeFaqs",
        meta: { title: "常见问题", icon: "document", keepAlive: true, params: { module: "faqs" } },
        children: [],
      },
      {
        path: "support-config",
        component: "life/resource/index",
        name: "LifeSupportConfig",
        meta: { title: "客服配置", icon: "phone", keepAlive: true, params: { module: "supportConfig" } },
        children: [],
      },
    ],
  },
  {
    path: "/images",
    component: "Layout",
    redirect: "/images/files",
    name: "LifeImages",
    meta: { title: "图片管理", icon: "picture", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "files",
        component: "life/images/index",
        name: "LifeImageLibrary",
        meta: { title: "图片库", icon: "picture", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "home-banners",
        component: "life/resource/index",
        name: "LifeHomeBanners",
        meta: { title: "首页轮播图", icon: "picture", keepAlive: true, params: { module: "homeBanners" } },
        children: [],
      },
    ],
  },
  {
    path: "/marketing",
    component: "Layout",
    redirect: "/marketing/coupons",
    name: "LifeMarketing",
    meta: { title: "营销管理", icon: "bell", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "coupons",
        component: "life/resource/index",
        name: "LifeCoupons",
        meta: { title: "优惠券", icon: "bell", keepAlive: true, params: { module: "coupons" } },
        children: [],
      },
      {
        path: "user-coupons",
        component: "life/resource/index",
        name: "LifeUserCoupons",
        meta: { title: "用户券明细", icon: "document", keepAlive: true, params: { module: "userCoupons" } },
        children: [],
      },
      {
        path: "promotion-links",
        component: "life/resource/index",
        name: "LifePromotionLinks",
        meta: { title: "视频号链接管理", icon: "wechat", keepAlive: true, params: { module: "promotionLinks" } },
        children: [],
      },
      {
        path: "member-cards",
        component: "life/resource/index",
        name: "LifeMemberCards",
        meta: { title: "会员卡模板", icon: "file", keepAlive: true, params: { module: "memberCards" } },
        children: [],
      },
      {
        path: "user-member-cards",
        component: "life/resource/index",
        name: "LifeUserMemberCards",
        meta: { title: "用户会员卡", icon: "file", keepAlive: true, params: { module: "userMemberCards" } },
        children: [],
      },
      {
        path: "member-card-records",
        component: "life/resource/index",
        name: "LifeMemberCardRecords",
        meta: { title: "会员卡流水", icon: "document", keepAlive: true, params: { module: "memberCardRecords" } },
        children: [],
      },
    ],
  },
  {
    path: "/audit",
    component: "Layout",
    redirect: "/audit/center",
    name: "LifeAudit",
    meta: { title: "审核中心", icon: "todo", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "center",
        component: "life/audit/index",
        name: "LifeAuditCenter",
        meta: { title: "待审核事项", icon: "todo", keepAlive: true, params: { type: "all" } },
        children: [],
      },
    ],
  },
  {
    path: "/system",
    component: "Layout",
    redirect: "/system/user",
    name: "LifeSystem",
    meta: { title: "系统管理", icon: "system", alwaysShow: true, hidden: false, params: {} },
    children: [
      {
        path: "user",
        component: "system/user/index",
        name: "User",
        meta: { title: "管理员", icon: "user", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "role",
        component: "system/role/index",
        name: "Role",
        meta: { title: "角色管理", icon: "role", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "menu",
        component: "system/menu/index",
        name: "SysMenu",
        meta: { title: "菜单/权限", icon: "menu", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "dict",
        component: "system/dict/index",
        name: "Dict",
        meta: { title: "字典管理", icon: "dict", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "log",
        component: "system/log/index",
        name: "Log",
        meta: { title: "操作日志", icon: "document", keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "dict-item",
        component: "system/dict/dict-item",
        name: "DictItem",
        meta: { title: "字典项", hidden: true, keepAlive: true, params: {} },
        children: [],
      },
      {
        path: "config",
        component: "system/config/index",
        name: "Config",
        meta: { title: "系统配置", icon: "setting", keepAlive: true, params: {} },
        children: [],
      },
    ],
  },
];
