services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: life_assistant_server
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./certs:/app/certs:ro
      - ./logs:/app/logs
    restart: unless-stopped
